[build]
  command = "npm run build"
  publish = "dist"

# Dla aplikacji SPA (React, Vite itp.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Po wysłaniu formularza contact przekierowuj na stronę /thankyou
[[redirects]]
  from = "/contact"
  to = "/thankyou"
  status = 303
